import re

def apply_symbolic_mapping(text):
    """
    Sustituye palabras comunes por operadores lógicos y símbolos 
    para reducir tokens antes del procesamiento del LLM.
    """
    mappings = {
        r'\buna\b': '1', r'\bun\b': '1',
        r'\bdos\b': '2',
        r'\btres\b': '3',
        r'\bcuatro\b': '4',
        r'\bcinco\b': '5',
        r'\bseis\b': '6',
        r'\bsiete\b': '7',
        r'\bocho\b': '8',
        r'\bnueve\b': '9',
        r'\bdiez\b': '10',
        r'\bcien\b': '100',
        r'\bmil\b': 'k',
        r'\bmillón\b': 'M',
        r'\bdiez mil\b': '10k',
        r'\bun millón\b': '1M',
        r'\by\b': '&', r'\btambién\b': '&',
        r'\bcon\b': 'w/',
        r'\bpara\b': '->',
        r'\bpor\b': '∋',
        r'\bentonces\b': '=>',
        r'\bsi\b': '?',
        r'\bno\b': '!',
        r'\bsin\b': 'w/o',
        r'\bsin embargo\b': '!',
        r'\ben\b': '@',
        r'\bde\b': '', r'\bdel\b': '', r'\bde la\b': '',
        r'\bcada\b': '∀', r'\btodos\b': '∀',
        r'\balgunos\b': '∃', r'\bexiste\b': '∃',
        r'\bpor ejemplo\b': 'e.g.', r'\bpor ej\b': 'e.g.',
        r'\bes decir\b': 'i.e.', r'\bsea\b': 'i.e.',
        r'\bigual a\b': '=', r'\biguales\b': '=',
        r'\bdiferente de\b': '!=', r'\bdiferentes\b': '!=',
        r'\bmayor que\b': '>', r'\bmayores\b': '>',
        r'\bmenor que\b': '<', r'\bmenores\b': '<',
        r'\bpero\b': '^',
        r'\bo\b': '|', r'\bu\b': '|',
        r'\bcomo\b': '~',
        r'\bcuando\b': '∇',
        r'\bantes\b': '←', r'\bantes de\b': '←',
        r'\bdespués\b': '→', r'\bdespués de\b': '→',
        r'\bentre\b': '⊂',
        r'\bsobre\b': '⊃',
        r'\bcontra\b': '≠',
        r'\bhacia\b': '→',
        r'\bhasta\b': '→',
        r'\bdesde\b': '←',
        r'\bacause\b': '∵',
        r'\bporque\b': '∵',
        r'\basi\b': '∴',
        r'\basí\b': '∴',
        r'\bpor lo tanto\b': '∴',
        r'\bademás\b': '+',
        r'\bmás\b': '+',
        r'\bmenos\b': '-',
        r'\bvez\b': '×',
        r'\btambi[eé]n\b': '+',
        r'\bal menos\b': '≥',
        r'\bmas\b': '+',
        r'\bmejor\b': '↑',
        r'\bpeor\b': '↓',
        r'\bfalta\b': '⊥',
        r'\bhay\b': '∃',
        r'\btenemos\b': '∋',
        r'\btener\b': '∋',
        r'\bser\b': '≡',
        r'\bestar\b': '≈',
        r'\brojo\b': '#F00', r'\bcarmesi\b': '#F00', r'\bescarlata\b': '#F00',
        r'\bnaranja\b': '#FA0', r'\bnaranaja\b': '#FA0',
        r'\bamarillo\b': '#FF0',
        r'\bverde\b': '#0F0', r'\besmeralda\b': '#0F0', r'\blima\b': '#0F0',
        r'\bazul\b': '#00F', r'\bceleste\b': '#0AF', r'\bazure\b': '#00F',
        r'\bvioleta\b': '#80F', r'\bmorado\b': '#80F', r'\bpurpura\b': '#80F',
        r'\brosa\b': '#F0A', r'\bflor\b': '#F0A',
        r'\bblanco\b': '#FFF',
        r'\bnegro\b': '#000', r'\bcarbon\b': '#000',
        r'\bgris\b': '#888', r'\bgris oscuro\b': '#444', r'\bgris claro\b': '#CCC',
        r'\bcafe\b': '#630', r'\bmarron\b': '#630', r'\bcastaño\b': '#630',
        r'\bcolor\b': 'clr', r'\bcolores\b': 'clr',
        r'\bfondo\b': 'bg', r'\btexto\b': 'txt', r'\bestilo\b': 'sty',
        
        r'\buna?\b': '1', r'\bdos\b': '2', r'\btres\b': '3',
        r'\btodos?\b': '∀', r'\balgunos?\b': '∃', r'\bninguno\b': '∅',
        r'\baproximadamente\b': '≈', r'\bmáximo\b': 'max', r'\bmínimo\b': 'min',
        
        r'\bactúa como\b': 'as:', r'\bes como\b': 'as:',
        r'\bescribe\b': 'gen:', r'\bexplica\b': 'exp:',
        r'\bresume\b': 'tl;dr:', r'\btraduce\b': 'tr:',
        r'\brevisa\b': 'check:', r'\bbusca\b': 'find:',
        r'\bayuda\b': 'help:', r'\bconsulta\b': 'qry:',
        
        r'\bahora\b': 'now', r'\bantes\b': 'prev', r'\bdespués\b': 'next',
        r'\bsiempre\b': '∞', r'\burgetne\b': '!', r'\bimportante\b': '!!',
        r'\bejemplo\b': 'ex:', r'\bpregunta\b': 'q:', r'\brespuesta\b': 'ans:',
        
        r'\bcon respecto a\b': 're', r'\bsobre\b': 're', r'\busando\b': 'using',
        r'\bincluyendo\b': 'inc', r'\bmediante\b': 'via',
        
        r'\blistas?\b': '[]', r'\barrays?\b': '[]',
        r'\bdiccionarios?\b': '{}', r'\bobjects?\b': '{}',
        r'\bcadenas?\b': 'str', r'\btexto\b': 'str',
        r'\bentero\b': 'int', r'\binteger\b': 'int',
        r'\bbooleano\b': 'bool', r'\bboolean\b': 'bool',
        r'\bparámetros?\b': 'args', r'\bargumentos?\b': 'args',
        r'\bvariable\b': 'var',
        
        r'\bsi entonces\b': 'if:', r'\bsi no\b': 'else:',
        r'\bsino\b': 'else:',
        r'\bmientras\b': 'while:',
        r'\bretornar\b': 'ret', r'\breturn\b': 'ret',
        r'\bverdadero\b': 'T', r'\btrue\b': 'T',
        r'\bfalso\b': 'F', r'\bfalse\b': 'F',
        r'\bes\s+igual\s+a\b': '==', r'\bequal\s+to\b': '==',
        r'\bdiferente\b': '!=',
        r'\bmás\s+igual\b': '+=',
        
        r'\bbase\s+de\s+datos\b': 'db', r'\bdatabase\b': 'db',
        r'\bservidor\b': 'srv', r'\bserver\b': 'srv',
        r'\busuario\b': 'usr', r'\buser\b': 'usr',
        r'\bcontraseña\b': 'pwd', r'\bpassword\b': 'pwd',
        r'\benlace\b': 'lnk', r'\blink\b': 'lnk',
        r'\bventana\b': 'win', r'\bwindow\b': 'win',
        r'\bbotón\b': 'btn', r'\bbutton\b': 'btn',
        
        r'\bprogramar\b': 'dev:', r'\bdesarrollar\b': 'dev:',
        r'\bcompilar\b': 'build:', r'\bbuild\b': 'build:',
        r'\bdesplegar\b': 'deploy:', r'\bdeploy\b': 'deploy:',
        r'\bcorregir\b': 'fix:', r'\bfix\b': 'fix:',
        r'\bbug\b': '🐞',
        r'\brefactorizar\b': 'refac:', r'\brefactor\b': 'refac:',
        r'\bcomentar\b': 'doc:', r'\bdocumentar\b': 'doc:',
        
        r'\bthought\b': '', r'\bthinking\b': '', r'\bthoughts\b': '',
        r'\bconsider\b': '', r'\bconsidering\b': '', r'\bconsideration\b': '',
        r'\beval\b': '', r'\bevaluating\b': '', r'\bevaluation\b': '',
        r'\banalyze\b': '', r'\banalyzing\b': '', r'\banalysis\b': '',
        r'\breason\b': '', r'\breasoning\b': '', r'\breasoned\b': '',
        r'\bstep\s+\d+\b': '', r'\bstep\d+\b': '',
        r'\bwe\s+(have|see|know)\b': '', r'\bfirst\b': '',
    }
        r'\breasoning\b': '', r'\bprocess\b': '',
        r'\bstep\s+\d+\b': '', r'\bbefore\b': '',
        r'\bwe\s+have\b': '', r'\bfirst\b': '',
    }
    
    for pattern, symbol in mappings.items():
        text = re.sub(pattern, symbol, text, flags=re.IGNORECASE)
    
    text = " ".join(text.split())
    
    return text